In [8]:
import numpy as np
import random

In [9]:
# Create an array with random elements of size 20x20
arr1 = np.random.randint(0,5,(20,20))
print(arr1)

[[1 0 4 2 4 0 3 4 4 4 4 2 4 4 3 3 3 0 1 0]
 [3 4 2 3 2 4 3 0 0 1 0 2 1 2 4 1 3 3 4 4]
 [3 1 1 2 2 2 1 0 1 2 1 0 4 1 0 2 2 2 3 0]
 [0 0 4 0 4 2 4 1 1 1 0 2 4 1 0 2 0 4 4 3]
 [4 4 4 1 0 1 3 4 1 0 4 2 1 4 0 3 0 3 0 2]
 [3 0 0 1 2 0 4 1 4 3 4 3 2 3 4 1 4 2 4 4]
 [2 4 0 0 3 3 2 3 1 3 0 1 3 2 2 3 3 1 2 3]
 [0 4 3 4 0 1 4 2 2 2 3 4 4 0 3 4 0 2 2 2]
 [1 0 1 3 4 3 1 0 4 1 4 0 0 0 4 3 0 4 3 4]
 [3 0 1 4 4 0 0 4 3 0 0 3 2 3 0 1 0 0 4 3]
 [0 3 1 0 0 0 2 4 1 4 3 4 1 3 4 1 2 4 0 3]
 [1 3 4 1 4 3 0 3 1 2 0 4 0 1 3 4 3 2 3 2]
 [0 4 4 2 0 4 3 1 3 2 4 3 3 3 2 2 4 0 1 1]
 [2 1 3 4 3 4 1 2 1 4 4 1 4 2 2 0 4 1 2 1]
 [3 3 1 4 1 1 0 2 4 0 4 4 1 3 4 2 3 2 0 3]
 [4 4 1 2 1 4 1 1 4 2 3 3 4 1 2 0 1 1 2 1]
 [4 3 3 0 1 4 1 2 3 1 2 1 3 1 4 0 0 1 3 4]
 [3 0 0 4 4 0 1 3 1 2 4 2 0 2 1 4 2 1 3 0]
 [0 3 2 1 2 2 2 1 2 2 2 0 2 0 0 1 0 1 2 0]
 [2 4 4 4 4 0 0 1 0 1 4 1 4 0 0 3 3 1 3 1]]


In [10]:
# Add zeros to the border of the array
pad_arr = np.pad(arr1, pad_width=1, mode='constant', constant_values=0)
print(pad_arr)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 4 2 4 0 3 4 4 4 4 2 4 4 3 3 3 0 1 0 0]
 [0 3 4 2 3 2 4 3 0 0 1 0 2 1 2 4 1 3 3 4 4 0]
 [0 3 1 1 2 2 2 1 0 1 2 1 0 4 1 0 2 2 2 3 0 0]
 [0 0 0 4 0 4 2 4 1 1 1 0 2 4 1 0 2 0 4 4 3 0]
 [0 4 4 4 1 0 1 3 4 1 0 4 2 1 4 0 3 0 3 0 2 0]
 [0 3 0 0 1 2 0 4 1 4 3 4 3 2 3 4 1 4 2 4 4 0]
 [0 2 4 0 0 3 3 2 3 1 3 0 1 3 2 2 3 3 1 2 3 0]
 [0 0 4 3 4 0 1 4 2 2 2 3 4 4 0 3 4 0 2 2 2 0]
 [0 1 0 1 3 4 3 1 0 4 1 4 0 0 0 4 3 0 4 3 4 0]
 [0 3 0 1 4 4 0 0 4 3 0 0 3 2 3 0 1 0 0 4 3 0]
 [0 0 3 1 0 0 0 2 4 1 4 3 4 1 3 4 1 2 4 0 3 0]
 [0 1 3 4 1 4 3 0 3 1 2 0 4 0 1 3 4 3 2 3 2 0]
 [0 0 4 4 2 0 4 3 1 3 2 4 3 3 3 2 2 4 0 1 1 0]
 [0 2 1 3 4 3 4 1 2 1 4 4 1 4 2 2 0 4 1 2 1 0]
 [0 3 3 1 4 1 1 0 2 4 0 4 4 1 3 4 2 3 2 0 3 0]
 [0 4 4 1 2 1 4 1 1 4 2 3 3 4 1 2 0 1 1 2 1 0]
 [0 4 3 3 0 1 4 1 2 3 1 2 1 3 1 4 0 0 1 3 4 0]
 [0 3 0 0 4 4 0 1 3 1 2 4 2 0 2 1 4 2 1 3 0 0]
 [0 0 3 2 1 2 2 2 1 2 2 2 0 2 0 0 1 0 1 2 0 0]
 [0 2 4 4 4 4 0 0 1 0 1 4 1 4 0 0 3 3 1 3 1 0]
 [0 0 0 0 0 0

In [11]:
# Created a 3D array of size 20x20x20
arr2 = np.random.randint(0,5,(20,20,20))
print(arr2)

[[[0 1 2 ... 3 4 2]
  [4 4 3 ... 2 1 1]
  [4 2 3 ... 3 2 3]
  ...
  [2 1 4 ... 2 0 4]
  [1 1 2 ... 2 4 2]
  [2 3 0 ... 3 4 0]]

 [[3 0 2 ... 1 0 2]
  [0 4 3 ... 1 0 2]
  [2 1 1 ... 3 0 4]
  ...
  [1 4 3 ... 0 4 1]
  [0 0 2 ... 1 4 4]
  [4 0 2 ... 2 2 2]]

 [[1 1 1 ... 0 4 1]
  [4 0 0 ... 1 4 4]
  [2 2 1 ... 1 3 0]
  ...
  [0 3 2 ... 3 4 1]
  [2 1 0 ... 4 3 0]
  [4 3 0 ... 0 0 1]]

 ...

 [[1 2 0 ... 3 2 2]
  [4 2 2 ... 1 2 4]
  [3 0 3 ... 0 4 3]
  ...
  [4 3 2 ... 2 2 3]
  [2 0 3 ... 4 0 0]
  [2 4 2 ... 1 1 2]]

 [[2 2 2 ... 1 1 3]
  [0 2 3 ... 1 4 1]
  [1 2 1 ... 1 2 2]
  ...
  [0 2 2 ... 0 2 0]
  [2 4 3 ... 3 1 2]
  [3 2 4 ... 0 3 0]]

 [[2 1 4 ... 3 1 3]
  [3 2 3 ... 0 4 3]
  [4 3 3 ... 4 1 2]
  ...
  [1 2 0 ... 3 0 3]
  [0 3 2 ... 0 3 0]
  [4 1 3 ... 4 2 2]]]


In [12]:
# Pad the 3D array with zeros on the border
pad_arr2 = np.pad(arr2, pad_width=1, mode='constant', constant_values=0)
print(pad_arr2)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 1 ... 4 2 0]
  [0 4 4 ... 1 1 0]
  ...
  [0 1 1 ... 4 2 0]
  [0 2 3 ... 4 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 3 0 ... 0 2 0]
  [0 0 4 ... 0 2 0]
  ...
  [0 0 0 ... 4 4 0]
  [0 4 0 ... 2 2 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 2 2 ... 1 3 0]
  [0 0 2 ... 4 1 0]
  ...
  [0 2 4 ... 1 2 0]
  [0 3 2 ... 3 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 2 1 ... 1 3 0]
  [0 3 2 ... 4 3 0]
  ...
  [0 0 3 ... 3 0 0]
  [0 4 1 ... 2 2 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [13]:
# Created a 3D array of size 20x40x10
arr3 = np.random.randint(0,5,(20,40,10))
print(arr3)

[[[2 1 1 ... 1 0 0]
  [3 3 4 ... 3 1 3]
  [0 3 3 ... 3 3 1]
  ...
  [3 1 2 ... 0 4 1]
  [4 1 4 ... 4 2 3]
  [1 2 2 ... 1 2 2]]

 [[4 2 4 ... 2 3 0]
  [1 3 0 ... 3 2 4]
  [2 2 0 ... 1 0 0]
  ...
  [4 4 4 ... 1 2 4]
  [0 2 1 ... 3 4 2]
  [4 1 3 ... 4 1 3]]

 [[2 3 2 ... 4 3 1]
  [2 2 1 ... 0 3 4]
  [0 2 0 ... 3 3 3]
  ...
  [2 3 1 ... 0 4 1]
  [1 2 2 ... 0 4 1]
  [2 2 4 ... 4 0 3]]

 ...

 [[2 3 3 ... 0 2 4]
  [1 3 2 ... 4 4 3]
  [1 3 1 ... 0 3 3]
  ...
  [1 0 4 ... 0 2 2]
  [3 4 1 ... 2 0 1]
  [2 2 3 ... 3 4 1]]

 [[3 2 2 ... 3 4 0]
  [4 4 1 ... 2 2 0]
  [2 4 1 ... 0 3 3]
  ...
  [0 2 1 ... 0 2 3]
  [1 2 4 ... 0 4 3]
  [2 2 1 ... 1 1 0]]

 [[4 4 0 ... 1 1 3]
  [2 2 3 ... 3 0 1]
  [2 3 4 ... 2 2 4]
  ...
  [3 2 4 ... 0 1 4]
  [3 2 4 ... 4 3 1]
  [1 2 3 ... 2 3 1]]]


In [14]:
# Pad the 3D array with zeros on the border
pad_arr3 = np.pad(arr3, pad_width=1, mode='constant', constant_values=0)
print(pad_arr3)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 2 1 ... 0 0 0]
  [0 3 3 ... 1 3 0]
  ...
  [0 4 1 ... 2 3 0]
  [0 1 2 ... 2 2 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 4 2 ... 3 0 0]
  [0 1 3 ... 2 4 0]
  ...
  [0 0 2 ... 4 2 0]
  [0 4 1 ... 1 3 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 3 2 ... 4 0 0]
  [0 4 4 ... 2 0 0]
  ...
  [0 1 2 ... 4 3 0]
  [0 2 2 ... 1 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 4 4 ... 1 3 0]
  [0 2 2 ... 0 1 0]
  ...
  [0 3 2 ... 3 1 0]
  [0 1 2 ... 3 1 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
