In [7]:
import random
import numpy as np

In [8]:
# Create a 4x4 array with random binary values
arr1 = np.random.randint(0,2,(4,4))
print(arr1)

[[0 0 0 1]
 [1 1 0 1]
 [0 0 1 1]
 [1 1 0 0]]


In [9]:
# Vector with as many rows as the matrix above with elements between 1 to 5
vec1 = np.random.randint(1,6,(4,1))
print(vec1)

[[4]
 [3]
 [1]
 [3]]


In [10]:
# Adding the vector to every column in the matrix
new_arr = arr1 + vec1
print(new_arr)

[[4 4 4 5]
 [4 4 3 4]
 [1 1 2 2]
 [4 4 3 3]]


In [11]:
# Multiplying every column in the matrix by the vector
mult_arr = arr1 @ vec1
print(mult_arr)

[[ 3]
 [10]
 [ 4]
 [ 7]]


In [12]:
# Multiplying every element in the matrix by a scalar value
scal_arr = 2 * arr1
print(scal_arr)

[[0 0 0 2]
 [2 2 0 2]
 [0 0 2 2]
 [2 2 0 0]]
