In [1]:
import random
import numpy as np

In [2]:
# Create a random 4x4 array
arr1 = np.random.rand(4,4)
print(arr1)

[[0.30729136 0.18827562 0.95053186 0.09325814]
 [0.72125269 0.34207401 0.89317226 0.58441678]
 [0.14420735 0.40778189 0.4827268  0.89583655]
 [0.04222031 0.58898506 0.77501188 0.68801155]]


In [3]:
# Find element at row 3 column 2
arr1[2, 1]

0.40778188783455793

In [4]:
# Find all even rows
arr1[1::2]

array([[0.72125269, 0.34207401, 0.89317226, 0.58441678],
       [0.04222031, 0.58898506, 0.77501188, 0.68801155]])

In [5]:
# Find all elements that are in the even rows and odd columns
arr1[1::2, ::2]

array([[0.72125269, 0.89317226],
       [0.04222031, 0.77501188]])

In [6]:
# Index all elements along the diagonal
arr1.diagonal()

array([0.30729136, 0.34207401, 0.4827268 , 0.68801155])

In [7]:
# Find the elements of the other diagonal
flipped_arr1 = np.fliplr(arr1) # Flip the matrix from left to right
flipped_arr1.diagonal()

array([0.09325814, 0.89317226, 0.40778189, 0.04222031])