In [23]:
import random
import numpy as np

In [24]:
# Create a random 4x4 array
arr1 = np.random.rand(4,4)
print(arr1)

[[0.31936244 0.18033126 0.52452048 0.45752202]
 [0.44287157 0.29827004 0.55944234 0.43595184]
 [0.01578766 0.29305463 0.32592047 0.13943258]
 [0.90747731 0.35886668 0.30316853 0.56749201]]


In [25]:
# Find element at row 3 column 2
arr1[2, 1]

0.2930546331399131

In [26]:
# Find all even rows
arr1[1::2]

array([[0.44287157, 0.29827004, 0.55944234, 0.43595184],
       [0.90747731, 0.35886668, 0.30316853, 0.56749201]])

In [27]:
# Find all elements that are in the even rows and odd columns
arr1[1::2, ::2]

array([[0.44287157, 0.55944234],
       [0.90747731, 0.30316853]])

In [38]:
# Index all elements along the diagonal
arr1.diagonal()

array([0.31936244, 0.29827004, 0.32592047, 0.56749201])

In [46]:
# Find the elements of the other diagonal
flipped_arr1 = np.fliplr(arr1) # Flip the matrix from left to right
flipped_arr1.diagonal()

array([0.45752202, 0.55944234, 0.29305463, 0.90747731])