In [8]:
import random
import numpy as np

In [9]:
# Create a random 4x4 array
arr1 = np.random.rand(4,4)
print(arr1)

[[0.20606533 0.54259685 0.74879019 0.04964128]
 [0.4473852  0.73860461 0.31441768 0.41428913]
 [0.98892977 0.50008691 0.83663912 0.01775257]
 [0.7044347  0.57401649 0.59464713 0.50962154]]


In [10]:
# Find element at row 3 column 2
arr1[2, 1]

0.5000869109210628

In [11]:
# Find all even rows
arr1[1::2]

array([[0.4473852 , 0.73860461, 0.31441768, 0.41428913],
       [0.7044347 , 0.57401649, 0.59464713, 0.50962154]])

In [12]:
# Find all elements that are in the even rows and odd columns
arr1[1::2, ::2]

array([[0.4473852 , 0.31441768],
       [0.7044347 , 0.59464713]])

In [13]:
# Index all elements along the diagonal
arr1.diagonal()

array([0.20606533, 0.73860461, 0.83663912, 0.50962154])

In [14]:
# Find the elements of the other diagonal
flipped_arr1 = np.fliplr(arr1) # Flip the matrix from left to right
flipped_arr1.diagonal()

array([0.04964128, 0.31441768, 0.50008691, 0.7044347 ])