In [1]:
import random
import numpy as np

In [2]:
# Create a random 4x4 array
arr1 = np.random.rand(4,4)
print(arr1)

[[0.7156124  0.35794508 0.17364374 0.17825686]
 [0.60858618 0.49387197 0.63325118 0.06958163]
 [0.32144514 0.80353589 0.48217449 0.41440617]
 [0.30835115 0.29665953 0.34512761 0.87590375]]


In [3]:
# Find element at row 3 column 2
arr1[2, 1]

0.8035358857088644

In [4]:
# Find all even rows
arr1[1::2]

array([[0.60858618, 0.49387197, 0.63325118, 0.06958163],
       [0.30835115, 0.29665953, 0.34512761, 0.87590375]])

In [5]:
# Find all elements that are in the even rows and odd columns
arr1[1::2, ::2]

array([[0.60858618, 0.63325118],
       [0.30835115, 0.34512761]])

In [6]:
# Index all elements along the diagonal
arr1.diagonal()

array([0.7156124 , 0.49387197, 0.48217449, 0.87590375])

In [7]:
# Find the elements of the other diagonal
flipped_arr1 = np.fliplr(arr1) # Flip the matrix from left to right
flipped_arr1.diagonal()

array([0.17825686, 0.63325118, 0.80353589, 0.30835115])